### ISSUE TITLE
 ERROR collecting tests/test_auth.py

### ISSUE THREAD

**Issue by Koalamanx** [kunaljubce/gmail-cleaner#16]
~/gmail-cleaner   main  pipenv run pytest                                                            ✔  3964  10:09:39
======================================================================= test session starts ========================================================================
platform darwin -- Python 3.8.18, pytest-7.4.4, pluggy-1.3.0
rootdir: /Users/xxx.xxx/gmail-cleaner
configfile: pytest.ini
collected 0 items / 1 error

============================================================================== ERRORS ==============================================================================
_______________________________________________________________ ERROR collecting tests/test_auth.py ________________________________________________________________
ImportError while importing test module '/Users/xxx.xxx/gmail-cleaner/tests/test_auth.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.pyenv/versions/3.8.18/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_auth.py:2: in <module>
    from src.main import Clingy
src/main.py:13: in <module>
    from src.export_archived_msgs_to_excel import export_archived_msgs
src/export_archived_msgs_to_excel.py:6: in <module>
    from archive_msg_metadata import db_conn
E   ModuleNotFoundError: No module named 'archive_msg_metadata'
===================================================================== short test summary info ======================================================================
ERROR tests/test_auth.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================= 1 error in 0.46s =======================================================================

**Comment by kunaljubce** [comment]
@Koalamanx Can you rebase your main (`git pull origin main`) and retry the tests please?

**Comment by kunaljubce** [comment]
@Koalamanx Closing this, please reopen if the issue persists!
